spring:
  application:
    name: clean-architecture
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:file:./data/db
    password: ''
  sql:
    init:
      mode: always
